apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: rnk-roboshop
type: Opaque
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: rnk-roboshop
  labels: # these labels are deployment labels
    app: payment
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: payment
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: payment
        project: roboshop
        tier: app
    spec:
      containers:
      - name: payment
        image: "{{ .Values.deployment.imageURL }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: rnk-roboshop
spec:
  selector:
    app: payment
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: payment
 namespace: rnk-roboshop
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: payment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: {{ .Values.hpa.cpuUtilization }} # usually 75 in real environment